title: Workload Planning Service Documentation
description: Warehouse workforce planning and resource allocation service
theme: jekyll-theme-cayman
baseurl: "/workload-planning-service"
url: "https://paklog.github.io"

# Navigation
navigation:
  - title: Home
    url: /
  - title: Architecture
    url: /architecture
  - title: Domain Model
    url: /DOMAIN-MODEL
  - title: Sequence Diagrams
    url: /SEQUENCE-DIAGRAMS
  - title: API Documentation
    url: /openapi

# GitHub
github:
  repository_url: https://github.com/paklog/workload-planning-service

# Build settings
markdown: kramdown
plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: false

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
